import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFileSync,existsSync,mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {chromium} from 'playwright';
// Supplemental owner verification. Static localhost + synthetic verified/owned adapter.
// NOT Worker/D1, production ownership, physical Safari, or physical speaker proof.
const OUT=resolve('evidence/gameplay-a-v1');mkdirSync(OUT,{recursive:true});
function wav(samples,rate){const b=Buffer.alloc(44+samples.length*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(rate,24);b.writeUInt32LE(rate*2,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(samples.length*2,40);samples.forEach((s,i)=>b.writeInt16LE(Math.round(Math.max(-1,Math.min(1,s))*32767),44+i*2));return b;}
function instrument(){
 const connect=AudioNode.prototype.connect;window.pcmTaps=[];
 // Observe the actual master->hardware destination connection; retain it unchanged.
 // A secondary real AudioContext captures MediaStream PCM even while music is suspended.
 AudioNode.prototype.connect=function(dest,...args){
  const result=connect.call(this,dest,...args);
  if(dest instanceof AudioDestinationNode && !this.context.__recorder && !this.__observed){
   this.__observed=true;const stream=this.context.createMediaStreamDestination();connect.call(this,stream);
   const rec=new AudioContext();rec.__recorder=true;const source=rec.createMediaStreamSource(stream.stream);
   const processor=rec.createScriptProcessor(2048,1,1),zero=rec.createGain();zero.gain.value=0;
   connect.call(source,processor);connect.call(processor,zero);connect.call(zero,rec.destination);
   const tap={music:this.context,rec,processor,source,stream,zero,chunks:[],rate:rec.sampleRate};
   processor.onaudioprocess=e=>tap.chunks.push(Array.from(e.inputBuffer.getChannelData(0)));
   pcmTaps.push(tap);rec.resume();
  }return result;
 };
}
async function mount(page,game,mode,closeMessages=true){await page.evaluate(async({game,mode})=>{
 window.saves=[];window.hintCalls=[];window.subs=new Set();window.exits=[];
 const save=game==='port-lucky'?{v:2,chapter:1,room:'suite',inv:['crackers'],flags:{minibarOpen:true,gotCrackers:true},scored:{},score:0,hintsUsed:0,revealed:{},px:150,py:160,dir:1,started:true,clock:null,done:false}:null;
 window.st={user:{id:'synthetic-owner-check',verified:true},entitlements:mode==='games'?[game]:[],save,catalog:{}};
 window.adapter={getState:async()=>structuredClone(st),subscribe:f=>{subs.add(f);return()=>subs.delete(f);},save:async(...a)=>{saves.push(a);return{updated_at:1};},listHints:async(...a)=>{hintCalls.push(a);return{revealed:[],count:0};},revealHint:async()=>{hintCalls.push('reveal');throw Error('No paid hints in objective verification');},checkout:async()=>{throw Error('Provider forbidden');}};
 const m=await import(`/${mode}/${game}/game.js`);window.handle=await m.mount(document.querySelector('#game'),adapter,{onExit:r=>exits.push(r)});
 },{game,mode});if(closeMessages)await dismiss(page);}
async function dismiss(page){for(let i=0;i<15;i++){const boxes=page.locator('.sierra:not(.death)');if(!await boxes.count())return;await boxes.first().click();}}
async function capture(page,name){await page.waitForTimeout(220);await page.evaluate(()=>{for(const t of pcmTaps)t.chunks=[];});await page.waitForTimeout(1100);const c=await page.evaluate(()=>{const t=pcmTaps.at(-1);return t?{samples:t.chunks.flat(),rate:t.rate,states:pcmTaps.map(t=>t.music.state)}:{samples:[],rate:48000,states:[]};});const rms=Math.sqrt(c.samples.reduce((s,x)=>s+x*x,0)/Math.max(1,c.samples.length));writeFileSync(resolve(OUT,name+'.wav'),wav(c.samples,c.rate));return{rms,samples:c.samples.length,rate:c.rate,states:c.states};}
for(const game of ['port-lucky','mop-galaxy'])for(const mode of ['games','demos'])test(`${game} ${mode}: owner supplemental rail, objective, canonical tap and real WebAudio`,{timeout:120000},async t=>{
 const id=`owner-${game}-${mode}`,report={scope:'Static local fixture; synthetic adapter, not Worker/D1/live or Safari proof',checks:[],audio:{},limitations:['Hidden/pagehide signals are explicitly dispatched lifecycle tests, not an OS-background simulation.','Demo Port Lucky has no public engine inspector: current-scene coverage restricted to its only Scene 1; no implementation extraction.']};
 const check=async(name,fn)=>{try{await fn();report.checks.push({name,pass:true});}catch(e){report.checks.push({name,pass:false,error:e.message});}};
 let browser;const server=createServer((req,res)=>{const p=new URL(req.url,'http://localhost').pathname;if(p==='/'){res.setHeader('content-type','text/html');res.end('<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0}</style><div id="game"></div>');return;}if(!['/context-input.js','/gameplay-controls.js'].includes(p)&&!/^\/(games|demos)\/(port-lucky|mop-galaxy)\/[a-z-]+\.(js|css)$/.test(p)){res.writeHead(404);res.end();return;}const f=resolve('public','.'+p);if(!existsSync(f)){res.writeHead(404);res.end();return;}res.setHeader('content-type',p.endsWith('.css')?'text/css':'text/javascript');res.end(readFileSync(f));});
 t.after(async()=>{writeFileSync(resolve(OUT,id+'.json'),JSON.stringify(report,null,2));await browser?.close();server.closeAllConnections();await new Promise(r=>server.close(r));});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({executablePath:process.env.RETRO_CHROMIUM||process.env.PL_CHROME||'/home/openclaw/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});
 const context=await browser.newContext({viewport:{width:844,height:390},hasTouch:true,isMobile:true});await context.addInitScript(instrument);const page=await context.newPage();page.setDefaultTimeout(3500);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}`);await mount(page,game,mode,false);
 await check('no AudioContext before legitimate gesture',async()=>{await page.waitForTimeout(200);report.gestureBaseline=await page.evaluate(()=>pcmTaps.map(t=>t.music.state));assert.deepEqual(report.gestureBaseline,[]);});await dismiss(page);
 for(const [width,height]of [[320,844],[390,844],[844,390],[1200,844]])await check(`six square rail geometry and canonical picker at ${width}x${height}`,async()=>{
  await page.setViewportSize({width,height});await page.waitForTimeout(150);const upright=page.getByRole('button',{name:'Play upright anyway',exact:true});if(await upright.isVisible())await upright.click();
  const rail=await page.locator('.side-actions').evaluate(el=>({buttons:[...el.querySelectorAll('button')].filter(b=>b.getBoundingClientRect().width>0).map(b=>{const r=b.getBoundingClientRect();return{id:b.dataset.rqUtility,name:b.getAttribute('aria-label'),x:r.x,y:r.y,w:r.width,h:r.height,right:r.right,bottom:r.bottom};}),overflow:document.documentElement.scrollWidth>innerWidth}));report[`rail${width}`]=rail;
  assert.deepEqual(rail.buttons.map(b=>b.id),['mute','objective','stuck','restart','exit','items']);assert.ok(!rail.overflow,'horizontal overflow');for(const b of rail.buttons){assert.ok(b.w>=44&&b.h>=44&&Math.abs(b.w-b.h)<1,JSON.stringify(b));assert.ok(b.x>=0&&b.right<=width&&b.y>=0&&b.bottom<=height,JSON.stringify(b));}
  const cv=page.locator('canvas').first();const r=await cv.boundingBox(),target=game==='port-lucky'?[166,66]:[112,122];const before=await page.evaluate(()=>JSON.stringify({inv:handle.state.inv,flags:handle.state.flags,score:handle.state.score}));await page.touchscreen.tap(r.x+target[0]*r.width/320,r.y+target[1]*r.height/180);await page.locator('.rq-context').waitFor();
  const canonical=await page.evaluate(async()=> (await import('/gameplay-controls.js')).VERBS.map(x=>x[1]));assert.deepEqual((await page.locator('.rq-context button').allTextContents()).slice(0,5),canonical);assert.equal(await page.evaluate(()=>JSON.stringify({inv:handle.state.inv,flags:handle.state.flags,score:handle.state.score})),before);
  await page.screenshot({path:resolve(OUT,`${id}-${width}.png`)});await page.keyboard.press('Escape');
 });
 await page.setViewportSize({width:844,height:390});await dismiss(page);
 await check('objective free current scene unchanged state and no hint calls',async()=>{const before=await page.evaluate(()=>({state:handle.state,hints:hintCalls.length}));await page.locator('[data-rq-utility=objective]').click();const goal=await page.locator('.modal-veil .modal p').innerText();report.goal=goal;const expected=game==='port-lucky'?'Get your bearings after last night and find a way out of the honeymoon suite.':'Find out what has changed aboard the Hyacinth and leave Deck 9.';assert.equal(goal,expected);await page.waitForTimeout(350);assert.deepEqual(await page.evaluate(()=>({state:handle.state,hints:hintCalls.length})),before);await page.locator('[data-rq-close]').click();});
 if(mode==='games')await check('late scene objective updates and existing modal pauses timer',async()=>{
  await page.evaluate(async({game})=>{const e=handle.engine;window.savedGame=e.game;const n=game==='port-lucky'?7:8;const {CHAPTER_START}=await import(`/games/${game}/script.js`);e.clearTransient();e.clearOverlays();e.game=CHAPTER_START(n);e.game.clock=game==='port-lucky'?600:200;e.view='game';e.updateHud();},{game});
  const before=await page.evaluate(()=>({chapter:handle.state.chapter,clock:handle.state.clock,hints:hintCalls.length}));await page.locator('[data-rq-utility=objective]').click();report.lateGoal=await page.locator('.modal-veil p').innerText();const expected=await page.evaluate(async({game})=>(await import(`/games/${game}/engine.js`)).SCENES[handle.state.chapter].objective,{game});assert.equal(report.lateGoal,expected);assert.equal(await page.evaluate(()=>handle.engine.clockActive()),true);const pausedClock=await page.evaluate(()=>handle.state.clock);await page.waitForTimeout(450);const during=await page.evaluate(()=>({clock:handle.state.clock,modalCount:handle.engine.modalCount,hints:hintCalls.length}));assert.equal(during.modalCount,1);assert.equal(during.hints,before.hints);assert.equal(during.clock,pausedClock,'challenge advances under objective modal');await page.locator('[data-rq-close]').click();assert.equal(await page.evaluate(()=>handle.engine.modalCount),0);await page.waitForTimeout(300);assert.ok(await page.evaluate(()=>handle.state.clock)<pausedClock,'clock does not resume after closing');await page.evaluate(()=>{handle.engine.game=savedGame;handle.engine.updateHud();});
 });
 await check('real oscillator PCM audible',async()=>{await page.keyboard.press('Escape');await page.locator('[data-rq-utility=objective]').click();await page.locator('[data-rq-close]').click();report.audio.audible=await capture(page,id+'-audible');assert.ok(report.audio.audible.samples>20000,'no continuous captured PCM');assert.ok(report.audio.audible.rms>0.0001,JSON.stringify(report.audio.audible));assert.equal(report.audio.audible.states.filter(s=>s==='running').length,1);});
 await check('mute PCM silence and persisted preference',async()=>{await page.getByRole('button',{name:'Mute music',exact:true}).click();report.audio.muted=await capture(page,id+'-muted');assert.ok(report.audio.muted.samples>20000);assert.ok(report.audio.muted.rms<0.000001,JSON.stringify(report.audio.muted));assert.equal(await page.evaluate(()=>localStorage.getItem('rq-music-muted')),'true');});
 await check('reload retains mute and gesture creates no playing track',async()=>{await page.reload();await mount(page,game,mode);await page.locator('[data-rq-utility=objective]').click();await page.locator('[data-rq-close]').click();assert.equal(await page.getByRole('button',{name:'Unmute music',exact:true}).count(),1);assert.equal(await page.evaluate(()=>pcmTaps.length),0);});
 await check('unmute resumes audible PCM',async()=>{await page.getByRole('button',{name:'Unmute music',exact:true}).click();report.audio.unmuted=await capture(page,id+'-unmuted');assert.ok(report.audio.unmuted.rms>0.0001);});
 await check('hidden visibility lifecycle suspend/resume (dispatched signal)',async()=>{await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});report.audio.hidden=await capture(page,id+'-hidden');assert.ok(report.audio.hidden.rms<0.000001);assert.ok(report.audio.hidden.states.every(s=>s!=='running'));await page.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});report.audio.visible=await capture(page,id+'-visible');assert.ok(report.audio.visible.rms>0.0001);});
 await check('pagehide/pageshow lifecycle (dispatched signal)',async()=>{await page.evaluate(()=>dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true})));report.audio.pagehide=await capture(page,id+'-pagehide');assert.ok(report.audio.pagehide.rms<0.000001);await page.evaluate(()=>dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true})));report.audio.pageshow=await capture(page,id+'-pageshow');assert.ok(report.audio.pageshow.rms>0.0001);});
 await check('unmount closes track; switched game inherits mute without duplicates',async()=>{await page.getByRole('button',{name:'Mute music',exact:true}).click();await page.evaluate(()=>handle.unmount());await page.waitForTimeout(200);assert.ok(await page.evaluate(()=>pcmTaps.every(t=>t.music.state==='closed')));assert.equal(await page.evaluate(()=>subs.size),0);await mount(page,game==='port-lucky'?'mop-galaxy':'port-lucky',mode);assert.equal(await page.getByRole('button',{name:'Unmute music',exact:true}).count(),1);assert.equal(await page.evaluate(()=>pcmTaps.filter(t=>t.music.state==='running').length),0);await page.getByRole('button',{name:'Unmute music',exact:true}).click();report.audio.switched=await capture(page,id+'-switched');assert.ok(report.audio.switched.rms>0.0001);assert.equal(report.audio.switched.states.filter(s=>s==='running').length,1);await page.evaluate(()=>handle.unmount());});
 await check('no runtime page errors',async()=>assert.deepEqual(errors,[]));report.errors=errors;
 assert.deepEqual(report.checks.filter(c=>!c.pass).map(c=>({name:c.name,error:c.error})),[]);
});
