import test from 'node:test';
import assert from 'node:assert/strict';
import {ContextInput} from '../public/context-input.js';
// Exercise installed listeners, not source-text regexes or replacement tap stubs.
class Target {
 constructor(){this.handlers=new Map();this.style={};this.children=[];}
 addEventListener(k,f){const a=this.handlers.get(k)||[];a.push(f);this.handlers.set(k,a);}
 removeEventListener(k,f){this.handlers.set(k,(this.handlers.get(k)||[]).filter(x=>x!==f));}
 emit(k,props={}){const ev={pointerType:'touch',pointerId:1,clientX:20,clientY:20,target:this,composedPath:()=>[this],stopImmediatePropagation(){this.stopped=true;},...props};for(const f of this.handlers.get(k)||[]){f(ev);if(ev.stopped)break;}return ev;}
 append(...x){this.children.push(...x);} remove(){this.removed=true;} setAttribute(){}
 getBoundingClientRect(){return {left:0,top:0,right:320,bottom:180};}
}
function fixture(){
 const win=new Target();Object.assign(win,{innerWidth:320,innerHeight:180});const doc=new Target();doc.defaultView=win;doc.createElement=()=>new Target();const cv=new Target();cv.ownerDocument=doc;const view=new Target();
 const spots=[{id:'s',name:'Object',actions:[{label:'Look',verb:'look'}]},{id:'n',name:'NPC',kind:'npc',actions:[{label:'Talk',verb:'talk'}]}];
 const e={cv,$:()=>view,game:{room:'r',chapter:1,inv:['item'],px:1,py:2},view:'game',account:{id:'A',verified:true},ent:{game:true},activeSpots:()=>spots,approach:(_s,f)=>{e.walkThen=f;},act:(...a)=>e.calls.push(a),calls:[],renderInv(){},renderVerbs(){},itemLabel:x=>x,clampWalk:(x,y)=>[x,y],onCanvasTap:()=>e.taps++,taps:0};
 const c=new ContextInput(e);e.context=c;c.wire();return {c,e,cv,doc,win,spots};
}
test('touch pointerup crosses shadow retargeting and synthesized click is suppressed',()=>{const {c,e,cv,doc}=fixture();cv.emit('pointerdown');doc.emit('pointerup',{target:{},composedPath:()=>[cv,doc]});assert.equal(e.taps,1);assert.equal(cv.emit('click',{pointerType:'touch'}).stopped,true);c.destroy();});
test('opening tap synthetic click cannot hit a newly overlaid menu button',()=>{const {c,e,cv,doc,spots}=fixture();e.onCanvasTap=()=>c.tap(spots[0]);cv.emit('pointerdown');doc.emit('pointerup',{composedPath:()=>[cv,doc]});const button=c.menu.children[1];assert.equal(doc.emit('click',{target:button,composedPath:()=>[button,c.menu,doc]}).stopped,true);assert.equal(c.selected.id,'s');assert.deepEqual(e.calls,[]);doc.emit('pointerdown',{target:button,composedPath:()=>[button,c.menu,doc]});assert.notEqual(doc.emit('click',{target:button,composedPath:()=>[button,c.menu,doc]}).stopped,true);c.destroy();});
test('drag, cancellation, and second pointer outside canvas never tap',()=>{for(const mode of ['drag','cancel','pinch']){const {c,e,cv,doc}=fixture();cv.emit('pointerdown');if(mode==='drag')doc.emit('pointermove',{clientX:70});if(mode==='cancel')doc.emit('pointercancel');if(mode==='pinch')doc.emit('pointerdown',{pointerId:2});doc.emit('pointerup',{target:cv,composedPath:()=>[cv,doc]});assert.equal(e.taps,0,mode);c.destroy();}});
test('hybrid real mouse stays verb-first, never object-first',()=>{const {c,e,cv}=fixture();cv.emit('pointerdown');cv.emit('pointercancel');cv.emit('pointerdown',{pointerType:'mouse'});assert.notEqual(cv.emit('click',{pointerType:'mouse'}).stopped,true);assert.equal(e.taps,0);c.destroy();});
test('destroy unregisters all listeners and prevents later context dispatch',()=>{const {c,e,cv,doc,win,spots}=fixture();c.tap(spots[0]);const s=c.selected;c.destroy();c.dispatch({verb:'look'},s);assert.equal(e.calls.length,0);for(const t of [cv,doc,win])assert.equal([...t.handlers.values()].flat().length,0);});
test('late old approach must not clear replacement target or execute stale action',()=>{const {c,e,spots}=fixture();c.tap(spots[0]);c.dispatch({verb:'take'});const old=e.walkThen;c.tap(spots[1]);old();assert.equal(c.selected?.id,'n');assert.deepEqual(e.calls,[]);c.destroy();});
test('picker preserves target, dispatches item once and rechecks ownership after approach',async()=>{const {c,e,spots}=fixture();c.tap(spots[1]);const s=c.selected;c.paint(true);assert.equal(c.selected,s);c.dispatch({verb:'use'},s,'item');const run=e.walkThen;e.game.inv=[];run();assert.equal(e.calls.length,0);c.tap(spots[1]);e.game.inv=['item'];c.dispatch({verb:'use'},c.selected,'item');const once=e.walkThen;once();once();assert.deepEqual(e.calls,[['use','n','item']]);c.destroy();});
test('hidden target, room, chapter, account, entitlement and dialogue invalidate delayed execution',()=>{for(const change of [f=>f.spots.length=0,f=>f.e.game.room='new',f=>f.e.game.chapter++,f=>f.e.account.id='B',f=>f.e.ent.game=false,f=>f.e.msgOpen=true]){const f=fixture();f.c.tap(f.spots[0]);f.c.dispatch({verb:'take'});const run=f.e.walkThen;change(f);run();assert.deepEqual(f.e.calls,[]);f.c.destroy();}});
const settled=()=>new Promise(r=>setImmediate(r));
test('authoritative entitlement is checked AGAIN after approach before canonical action',async()=>{const {c,e,spots}=fixture();let allowed=true,reads=0;e.adapter={getState:async()=>{reads++;return{user:{id:'A',verified:true},entitlements:allowed?['port-lucky']:[]};}};c.tap(spots[0]);c.dispatch({verb:'take'});await settled();assert.equal(typeof e.walkThen,'function');allowed=false;e.walkThen();await settled();assert.equal(reads,2);assert.deepEqual(e.calls,[]);assert.equal(c.pending,false);c.destroy();});
test('late authorization denial cannot dismiss replacement menu',async()=>{const {c,e,spots}=fixture();let resolve;e.adapter={getState:()=>new Promise(r=>resolve=r)};c.tap(spots[0]);c.dispatch({verb:'take'});c.tap(spots[1]);resolve({user:null,entitlements:[]});await settled();assert.equal(c.selected.id,'n');assert.deepEqual(e.calls,[]);c.destroy();});
test('Walk to is movement only, never Go or script use',()=>{const {c,e,spots}=fixture();spots[0].at=[33,44];c.tap(spots[0]);c.dispatch({verb:'walk'});assert.deepEqual(e.walkTarget,[33,44]);assert.equal(e.walkThen,null);assert.deepEqual(e.calls,[]);c.destroy();});
test('blocked gesture start and resize cannot later become taps or queued actions',()=>{const {c,e,cv,doc,win,spots}=fixture();e.msgOpen=true;cv.emit('pointerdown');e.msgOpen=false;doc.emit('pointerup',{target:cv,composedPath:()=>[cv]});assert.equal(e.taps,0);c.tap(spots[0]);c.dispatch({verb:'take'});const old=e.walkThen;cv.emit('pointerdown');win.emit('resize');old();doc.emit('pointerup',{target:cv,composedPath:()=>[cv]});assert.equal(e.taps,0);assert.deepEqual(e.calls,[]);c.destroy();});
