import test from 'node:test';
import assert from 'node:assert/strict';
import {captureScene, gameplaySnapshot, sceneProgress, rewindScene, saveGameplay, validHistory} from '../public/scene-history.js';
import {scoreDisplay} from '../public/gameplay-controls.js';
import {SCENES as PS, Engine as PE} from '../public/games/port-lucky/engine.js';
import {SCENES as MS} from '../public/games/mop-galaxy/engine.js';
import {POINTS as PP} from '../public/games/port-lucky/data.js';
import {POINTS as MP} from '../public/games/mop-galaxy/data.js';
import {migrateSave as pm} from '../public/games/port-lucky/script.js';
import {migrateSave as mm} from '../public/games/mop-galaxy/script.js';
const raw=(chapter=1)=>({v:2,ownerId:'A',chapter,room:'r'+chapter,inv:['distinctive'],flags:{tokens:2,o2:17},scored:{},score:0,px:23,py:140,dir:-1,clock:98,done:false,hintsUsed:0,revealed:{}});
const config={id:'test-game',scenes:{1:{name:'One'},2:{name:'Two'},3:{name:'Three'}},rooms:{r1:{},r2:{},r3:{}},items:{distinctive:{}},roomChapter:{r1:1,r2:2,r3:3}};
function engine(){return {game:raw(),account:{id:'A',verified:true},ent:{game:true},adapter:{save:async()=>({updated_at:1})},clearTransient(){this.lastSnap=null;},clearOverlays(){},renderInv(){},updateHud(){},updateClockUI(){},script:{onRestart(){}},setSaveState(s){this.saveState=s;}};}
test('legacy current checkpoints preserved byte-for-byte, never promoted or replaced on migration',()=>{
  for(const [migrate,room]of [[pm,'bar'],[mm,'galley']]){
    const old={v:2,chapter:3,room,inv:[],flags:{distinctive:true},scored:{},score:17,checkpoint:{chapter:3,room,inv:[],flags:{actualMarker:true},score:12}};
    const migrated=migrate(old);assert.deepEqual(migrated.checkpoint,old.checkpoint);assert.equal(migrated.history,undefined);assert.equal(migrated.score,17);assert.equal(migrated.flags.distinctive,true);
  }
});
test('history rejects hidden recursive payload, excessive depth and malformed quantities without losing old checkpoint',()=>{
  for(const mutate of [s=>s.flags.history={},s=>s.money=-1,s=>s.flags.tokens=-1,s=>{let d=s.flags;for(let i=0;i<12;i++)d=d.deep={};}]){
    const g=raw();captureScene(g,config);const old=g.history;g.history=structuredClone(old);mutate(g.history.starts[1]);assert.equal(validHistory(g.history,g,config),false);
  }
  const g=raw();g.flags.blob='x'.repeat(21000);assert.throws(()=>captureScene(g,config),/save exceeds/);assert.equal(g.history,undefined);
});
test('revoked paid run cannot rewind even into first-scene history',async()=>{const e=engine();captureScene(e.game,config);Object.assign(e.game,raw(2));captureScene(e.game,config);e.ent.game=false;await assert.rejects(rewindScene(e,1,config));assert.equal(e.game.chapter,2);});
test('in-flight legitimate hint accounting settles before snapshot commit',async()=>{
  const e=engine();captureScene(e.game,config);Object.assign(e.game,raw(2));captureScene(e.game,config);
  let release;const work=new Promise(r=>release=()=>{e.game.hintsUsed=3;e.game.revealed={paid:2};r();});e.sceneHintWork=new Set([work]);
  let calls=0;e.adapter.save=async(id,data)=>{calls++;assert.equal(data.hintsUsed,3);assert.deepEqual(data.revealed,{paid:2});return {updated_at:1};};
  const reset=rewindScene(e,1,config);await Promise.resolve();assert.equal(calls,0);release();await reset;assert.equal(e.game.hintsUsed,3);
});
test('actual scene checkpoints immutable, bounded, no recursive snapshots and no reload replacement',()=>{const e=engine();captureScene(e.game,config);const first=structuredClone(e.game.history.starts[1]);e.game.inv.push('later');e.game.flags.tokens=0;captureScene(e.game,config);assert.deepEqual(e.game.history.starts[1],first);assert.equal(gameplaySnapshot(e.game).history,undefined);for(let n=2;n<=3;n++){Object.assign(e.game,raw(n));captureScene(e.game,config);}assert.deepEqual(e.game.history.completed,[1,2]);assert.equal(Object.keys(e.game.history.starts).length,3);assert.ok(validHistory(e.game.history,e.game,config));assert.ok(JSON.stringify(e.game).length<10000);});
test('completed history list has honest unavailable legacy entries, no guessed history',()=>{const g=raw(3);assert.deepEqual(sceneProgress(g,config).map(s=>[s.chapter,s.state,s.available]),[[1,'completed',false],[2,'completed',false],[3,'current',false]]);const old=pm({v:2,chapter:3,room:'bar',flags:{},inv:[],score:0});assert.equal(old.checkpoint,undefined);assert.equal(old.history,undefined);});
test('durable exact rewind trims future, preserves financial hint policy and clears stale snapshots',async()=>{const e=engine();captureScene(e.game,config);Object.assign(e.game,raw(2));captureScene(e.game,config);const start=structuredClone(e.game.history.starts[2]);Object.assign(e.game,raw(3));captureScene(e.game,config);e.game.flags.tokens=0;e.game.hintsUsed=4;e.game.revealed={paid:2};e.game.done=true;let written;e.adapter.save=async(id,data,opts)=>{written=structuredClone(data);assert.equal(e.paused,true);assert.equal(e.game.chapter,3);return {updated_at:1};};await rewindScene(e,2,config);assert.deepEqual(gameplaySnapshot(e.game),{...start,hintsUsed:4,revealed:{paid:2},done:false});assert.deepEqual(e.game.history.completed,[1]);assert.deepEqual(Object.keys(e.game.history.starts),['1','2']);assert.deepEqual(written,e.game);assert.equal(e.lastSnap,null);assert.equal(e.paused,false);});
test('save error and CAS conflict retain usable exact pre-reset state; double confirm refused',async()=>{for(const status of [503,409]){const e=engine();captureScene(e.game,config);Object.assign(e.game,raw(2));captureScene(e.game,config);const before=structuredClone(e.game);let reject;e.adapter.save=()=>new Promise((_,r)=>reject=r);const p=rewindScene(e,1,config);await assert.rejects(rewindScene(e,1,config),/pending/);while(!reject)await new Promise(r=>setTimeout(r,0));reject(Object.assign(new Error('save failed'),{status}));await assert.rejects(p,/save failed/);assert.deepEqual(e.game,before);assert.equal(e.paused,false);}});
test('ordinary save drains before reset; saves while paused cannot overwrite reset',async()=>{const e=engine();captureScene(e.game,config);Object.assign(e.game,raw(2));captureScene(e.game,config);let release;const writes=[];e.adapter.save=async(id,g)=>{writes.push(g.chapter);if(writes.length===1)await new Promise(r=>release=r);return {updated_at:1};};const save=saveGameplay(e,config,false);const rewind=rewindScene(e,1,config);await saveGameplay(e,config,true);assert.deepEqual(writes,[2]);release();await Promise.all([save,rewind]);assert.deepEqual(writes,[2,1]);assert.equal(e.game.chapter,1);});
test('wrong owner/game, revoked paid access, corrupted/version/oversized histories rejected',async()=>{for(const mutate of [e=>e.account=null,e=>e.account.id='B',e=>e.ent.game=false,e=>e.game.history.gameId='wrong',e=>e.game.history.version=99,e=>e.game.history.starts[2].inv=['alien'],e=>e.game.history.starts[2].flags.blob='x'.repeat(60000)]){const e=engine();captureScene(e.game,config);Object.assign(e.game,raw(2));captureScene(e.game,config);Object.assign(e.game,raw(3));captureScene(e.game,config);e.game.history=structuredClone(e.game.history);mutate(e);let called=0;e.adapter.save=async()=>{called++;};await assert.rejects(rewindScene(e,2,config));assert.equal(called,0);}});
test('account change/unmount during save cannot install abandoned rewind',async()=>{for(const cancel of [e=>e.account.id='B',e=>e.destroyed=true]){const e=engine();captureScene(e.game,config);Object.assign(e.game,raw(2));captureScene(e.game,config);let release;e.adapter.save=()=>new Promise(r=>release=r);const p=rewindScene(e,1,config);while(!release)await new Promise(r=>setTimeout(r,0));cancel(e);release({updated_at:1});await assert.rejects(p,/changed/);assert.equal(e.game.chapter,2);}});
for(const [name,scenes,points,maxes] of [['Port',PS,PP,[25,25,35,35,35,30,45,20]],['Mop',MS,MP,[20,25,35,35,30,30,45,30]]])test(name+' actual legal scene max allocation totals 250; initial and unknown score denominators',()=>{assert.deepEqual(Object.values(scenes).map(s=>s.max),maxes);assert.equal(maxes.reduce((a,b)=>a+b,0),250);for(let n=1;n<=8;n++)assert.equal(scoreDisplay({chapter:n,score:0,scored:{}},scenes,points),`Scene: 0 / ${maxes[n-1]} | Total: 0 / 250`);assert.equal(scoreDisplay({chapter:4,score:99,scored:{legacy:true}},scenes,points),`Scene: unknown / ${maxes[3]} | Total: 99 / 250`);});
