// Actual workerd + isolated LOCAL D1. Synthetic events are not live fulfilment.
import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';import fs from 'node:fs';
import {api,sql,q,ids,E,reset} from './local-control.js';
const results=[];async function check(name,fn){try{await fn();results.push({name,status:'pass'});console.log('PASS',name);}catch(e){results.push({name,status:'fail',error:e.stack});console.log('FAIL',name,e.message);}}
const json=async r=>{assert.equal(r.status,200,await r.clone().text());return r.json();};
const raw=(p='buyer')=>({v:2,ownerId:ids[p],chapter:1,room:'closet',inv:['mop'],flags:{},scored:{},score:0,hintsUsed:0,revealed:{},px:150,py:160,dir:1,started:true,clock:null,checkpoint:null,done:false});
const n=Math.floor(Date.now()/1000);
sql(`DELETE FROM saves WHERE user_id=${q(ids.buyer)};DELETE FROM hint_reveals WHERE user_id=${q(ids.buyer)};DELETE FROM entitlement_contributions WHERE user_id=${q(ids.buyer)};`);
async function event(id,type,obj){const body=JSON.stringify({id,type,data:{object:obj}}),t=Math.floor(Date.now()/1000),sig=createHmac('sha256','synthetic-mop-local-signature-only').update(t+'.'+body).digest('hex');return api(null,'/api/stripe/webhook',{method:'POST',raw:body,headers:{'stripe-signature':`t=${t},v1=${sig}`}});}
await check('local config/catalogue 799+199 USD sales disabled with server headers',async()=>{const c=await json(await api(null,'/api/config'));assert.equal(c.catalog['mop-galaxy'].price_cents,799);assert.equal(c.catalog['mop-galaxy-walkthrough'].price_cents,199);assert.equal(c.catalog['mop-galaxy-walkthrough'].requires,'mop-galaxy');assert.equal(c.saleEnabled,false);const r=await api(null,'/');assert.equal(r.headers.get('cache-control'),'no-store');assert.equal(r.headers.get('x-content-type-options'),'nosniff');});
await check('exact ownership asset gates independent both games; public demo anonymous',async()=>{for(const p of ['anon','free','port','owner','both']){for(const g of ['port-lucky','mop-galaxy']){const expected=p==='anon'?401:(p==='both' || (p==='port' && g==='port-lucky') || (p==='owner' && g==='mop-galaxy'))?200:402;assert.equal((await api(p,'/games/'+g+'/game.js')).status,expected,p+' '+g);}}assert.equal((await api('anon','/demos/mop-galaxy/game.js')).status,200);});
await check('shared/server/source/encoded/nested protected paths denied',async()=>{for(const p of ['/games/_shared/engine.js','/src/games/mop-galaxy-hints.js','/evidence/mop-galaxy-v1/inputs/public/games/mop-galaxy/script.js','/games/mop-galaxy/%73cript.js','/games/mop-galaxy/nested/script.js','/games/mop-galaxy/hints.js'])assert.equal((await api('both',p)).status,404,p);});
await check('real checkout rejects non-owner walkthrough, rollout and wrong origin without provider',async()=>{assert.equal((await api('buyer','/api/checkout',{method:'POST',data:{sku:'mop-galaxy-walkthrough'}})).status,409);assert.equal((await api('buyer','/api/checkout',{method:'POST',data:{sku:'mop-galaxy'}})).status,503);assert.equal((await api('buyer','/api/checkout',{method:'POST',data:{sku:'mop-galaxy'},headers:{origin:'https://wrong.example.test'}})).status,403);});
await check('actual D1 CAS eight writers one acknowledgement seven conflicts',async()=>{reset('buyer');const d={game_id:'mop-galaxy',version:1,revision:0,ownerId:ids.buyer,data:raw()};const r=await Promise.all(Array.from({length:8},()=>api('buyer','/api/save',{method:'PUT',data:d})));assert.equal(r.filter(x=>x.status===200).length,1);assert.equal(r.filter(x=>x.status===409).length,7);const ack=await json(r.find(x=>x.status===200));assert.equal(ack.acknowledged,true);assert.equal(ack.revision,1);});
await check('save owner/free scene/checkpoint boundaries reject without mutation',async()=>{const before=(await json(await api('buyer','/api/me'))).save_envelopes['mop-galaxy'];for(const [data,status] of [[{...raw(),ownerId:ids.owner},409],[{...raw(),room:'cryo',chapter:2},400],[{...raw(),checkpoint:{...raw(),chapter:2,room:'cryo'}},400],[{...raw(),revealed:{'snack-tool':2},hintsUsed:3},400]])assert.equal((await api('buyer','/api/save',{method:'PUT',data:{game_id:'mop-galaxy',version:1,revision:1,ownerId:ids.buyer,data}})).status,status);assert.deepEqual((await json(await api('buyer','/api/me'))).save_envelopes['mop-galaxy'],before);});
await check('separate games/accounts have distinct D1 save envelopes',async()=>{const r=await api('buyer','/api/save',{method:'PUT',data:{game_id:'port-lucky',version:1,revision:0,ownerId:ids.buyer,data:{room:'suite',inv:[],flags:{},score:0}}});assert.equal(r.status,200);const me=await json(await api('buyer','/api/me'));assert.equal(me.save_envelopes['mop-galaxy'].data.room,'closet');assert.equal(me.save_envelopes['port-lucky'].data.room,'suite');assert.equal((await json(await api('admin','/api/me'))).save_envelopes['mop-galaxy'],undefined);});
const done=(id,sku,pi,amount)=>({id,payment_status:'paid',currency:'usd',amount_total:amount,payment_intent:pi,client_reference_id:ids.buyer,metadata:{user_id:ids.buyer,sku,game_id:sku.replace(/-walkthrough$/,'')}});
sql(`DELETE FROM receipt_outbox WHERE purchase_id LIKE 'cs_mg_local_%';DELETE FROM entitlement_contributions WHERE user_id=${q(ids.buyer)};DELETE FROM purchases WHERE id LIKE 'cs_mg_local_%';DELETE FROM stripe_events WHERE id LIKE 'evt_mg_local_%';DELETE FROM payment_terminals WHERE payment_intent LIKE 'pi_mg_local_%';INSERT INTO purchases(id,user_id,sku,amount_cents,currency,status,created_at) VALUES('cs_mg_local_game',${q(ids.buyer)},'mop-galaxy',799,'usd','pending',${n}),('cs_mg_local_walk',${q(ids.buyer)},'mop-galaxy-walkthrough',199,'usd','pending',${n}),('cs_mg_local_port',${q(ids.buyer)},'port-lucky',799,'usd','pending',${n});`);
await check('synthetic signed local completion wrong game/amount/signature fails closed',async()=>{let d=done('cs_mg_local_game','mop-galaxy','pi_mg_local_game',799);assert.equal((await api(null,'/api/stripe/webhook',{method:'POST',raw:'{}',headers:{'stripe-signature':'invalid'}})).status,400);assert.equal((await event('evt_mg_local_wrong','checkout.session.completed',{...d,metadata:{...d.metadata,game_id:'port-lucky'}})).status,400);assert.equal((await event('evt_mg_local_amount','checkout.session.completed',{...d,amount_total:199})).status,400);assert.ok(!(await json(await api('buyer','/api/me'))).entitlements.includes('mop-galaxy'));});
await check('synthetic signed local completion duplicate events grant exact game once; failed receipt honest',async()=>{const d=done('cs_mg_local_game','mop-galaxy','pi_mg_local_game',799);const r=await Promise.all(Array.from({length:6},()=>event('evt_mg_local_game','checkout.session.completed',d)));assert.ok(r.every(x=>x.status===200));const me=await json(await api('buyer','/api/me'));assert.deepEqual(me.entitlements,['mop-galaxy']);const detail=await json(await api('admin','/api/admin/users/'+ids.buyer));assert.equal(detail.purchases.filter(x=>x.sku==='mop-galaxy'&&x.status==='paid').length,1);});
await check('actual hint API tiers/authorization/history format isolated per game',async()=>{assert.equal((await api('buyer','/api/hint',{method:'POST',data:{game_id:'mop-galaxy',puzzle_id:'snack-tool',level:0}})).status,402);await json(await event('evt_mg_local_walk','checkout.session.completed',done('cs_mg_local_walk','mop-galaxy-walkthrough','pi_mg_local_walk',199)));assert.equal((await api('buyer','/api/hint',{method:'POST',data:{game_id:'mop-galaxy',puzzle_id:'snack-tool',level:1}})).status,409);const h=await json(await api('buyer','/api/hint',{method:'POST',data:{game_id:'mop-galaxy',puzzle_id:'snack-tool',level:0}}));assert.match(h.text,/doing a job already/);const list=await json(await api('buyer','/api/hints?game=mop-galaxy'));assert.equal(list.revealed.length,1);assert.equal(list.count,1);assert.equal((await json(await api('buyer','/api/hints?game=port-lucky'))).revealed.length,0);});
await check('full refund isolates Mop game/walkthrough and retains other game plus saves',async()=>{await json(await event('evt_mg_local_port','checkout.session.completed',done('cs_mg_local_port','port-lucky','pi_mg_local_port',799)));const before=(await json(await api('buyer','/api/me'))).save_envelopes;await json(await event('evt_mg_local_refund','charge.refunded',{payment_intent:'pi_mg_local_game',refunded:true,amount:799,amount_refunded:799}));const me=await json(await api('buyer','/api/me'));assert.deepEqual(me.entitlements,['port-lucky']);assert.deepEqual(me.save_envelopes,before);assert.equal((await api('buyer','/games/mop-galaxy/game.js')).status,402);assert.equal((await api('buyer','/games/port-lucky/game.js')).status,200);assert.equal((await api('buyer','/api/hint',{method:'POST',data:{game_id:'mop-galaxy',puzzle_id:'snack-tool',level:0}})).status,402);});
await check('late synthetic paid replay cannot revive refunded Mop',async()=>{await json(await event('evt_mg_local_late','checkout.session.completed',done('cs_mg_local_game','mop-galaxy','pi_mg_local_game',799)));assert.deepEqual((await json(await api('buyer','/api/me'))).entitlements,['port-lucky']);});
await check('actual admin per-SKU stats/detail effective dependency and hint history',async()=>{const stats=await json(await api('admin','/api/admin/stats'));assert.ok(JSON.stringify(stats).includes('mop-galaxy'));const detail=await json(await api('admin','/api/admin/users/'+ids.buyer));assert.deepEqual(detail.entitlements.map(x=>x.sku),['port-lucky']);assert.ok(JSON.stringify(detail).includes('mop-galaxy'));});
fs.writeFileSync(E+'/runtime-results.json',JSON.stringify({runtime:'LOCAL workerd/D1, synthetic signatures not live Stripe',results,pass:results.filter(x=>x.status==='pass').length,fail:results.filter(x=>x.status==='fail').length},null,2));process.exitCode=results.some(x=>x.status==='fail')?1:0;
