import test from 'node:test';
import assert from 'node:assert/strict';
import {createPortLuckyAdapter,createPortLuckyHost} from '../../public/port-lucky-platform.js';
import {createMopGalaxyAdapter,createMopGalaxyHost} from '../../public/mop-galaxy-platform.js';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
async function until(fn){for(let i=0;i<300;i++){if(fn())return;await sleep(2);}throw new Error('Deterministic gate not reached');}
const games=[['port-lucky',createPortLuckyAdapter,createPortLuckyHost,'suite'],['mop-galaxy',createMopGalaxyAdapter,createMopGalaxyHost,'closet']];
const raw=(game,room,score=0)=>({v:2,ownerId:'A',chapter:1,room,inv:[],flags:{},scored:{},score,hintsUsed:0,revealed:{},px:150,py:160,dir:1,started:true,clock:null,checkpoint:null,done:false});
function fixture(game,room){const f={me:{user:{id:'A',verified:true},entitlements:[game,game+'-walkthrough'],save_envelopes:{}},calls:[],hook:null,serverRev:0};f.fetch=async(p,o)=>{f.calls.push({p,o});if(f.hook){const r=await f.hook(p,o);if(r)return r;}if(p==='/api/me')return Response.json(f.me);if(p==='/api/config')return Response.json({catalog:{}});if(p==='/api/save'){const b=JSON.parse(o.body);if(b.revision!==f.serverRev)return Response.json({error:'Save conflict'},{status:409});f.serverRev++;return Response.json({acknowledged:true,revision:f.serverRev,updated_at:123});}return Response.json({text:'guarded hint',revealed:[],count:13});};return f;}
for(const [game,make,hostFactory,room] of games){
 for(const method of ['revealHint','listHints'])for(const phase of ['before','after'])test(`${game}: ${method} ${phase} refresh survives same-identity polling/save refresh`,async()=>{const f=fixture(game,room),b=make({fetch:f.fetch});await b.refresh();const gate=deferred();let held=false,reads=0;f.hook=async p=>{if(p==='/api/me' && ++reads===(phase==='before'?1:2)){held=true;return gate.promise;}};const action=method==='listHints'?b.adapter.listHints(game):b.adapter.revealHint(game,'synthetic',0);const observed=action.then(x=>({x}),e=>({e}));await until(()=>held);const poll=b.refresh().catch(e=>({error:e}));gate.resolve(Response.json(f.me));const out=await observed;await poll;assert.equal(out.e,undefined);assert.equal(method==='listHints'?out.x.count:out.x.text,method==='listHints'?13:'guarded hint');b.dispose();});
 test(`${game}: delayed checkout cannot navigate switched account; POST pins owner`,async()=>{const f=fixture(game,room),b=make({fetch:f.fetch}),gate=deferred(),assigned=[];const original=globalThis.location;globalThis.location={assign:u=>assigned.push(u)};let posted;try{await b.refresh();f.hook=(p,o)=>{if(p==='/api/checkout'){posted=JSON.parse(o.body);return gate.promise;}};const action=b.adapter.checkout(game),observed=assert.rejects(action,e=>e.code==='STATE_CHANGED');await until(()=>posted);f.me.user={id:'B',verified:true};gate.resolve(Response.json({url:'https://checkout.stripe.com/c/pay/synthetic-only'}));await observed;assert.deepEqual(assigned,[]);assert.equal(posted.ownerId,'A');}finally{b.dispose();globalThis.location=original;}});
 test(`${game}: disposed cold import cannot commit state`,async()=>{const f=fixture(game,room),gate=deferred();f.me.save_envelopes[game]={version:1,revision:0,data:raw(game,room)};let entered=false,published=0;const b=make({fetch:f.fetch,onState:()=>published++,loadGame:async()=>{entered=true;await gate.promise;return {rooms:{[room]:{}},DEFINITION:{validateSave:()=>true}};}});const pending=b.refresh(),observed=pending.then(x=>({x}),e=>({e}));try{await until(()=>entered);b.dispose();gate.resolve();const out=await observed;assert.equal(out.e?.code,'STATE_CHANGED');assert.equal(published,0);}finally{b.dispose();gate.resolve();await observed;}});
 for(const change of ['logout','switch','refund','unverified','dispose'])test(`${game}: delayed hint still rejects real ${change}`,async()=>{const f=fixture(game,room),b=make({fetch:f.fetch}),gate=deferred();await b.refresh();let held=false;f.hook=p=>{if(p==='/api/hint'){held=true;return gate.promise;}};const pending=b.adapter.revealHint(game,'synthetic',0),observed=assert.rejects(pending,e=>e.code==='STATE_CHANGED');await until(()=>held);if(change==='dispose')b.dispose();else {if(change==='logout')f.me.user=null;if(change==='switch')f.me.user={id:'B',verified:true};if(change==='refund')f.me.entitlements=[game];if(change==='unverified')f.me.user.verified=false;await assert.rejects(b.refresh(),e=>e.code==='STATE_CHANGED');}gate.resolve(Response.json({text:'private answer'}));await observed;b.dispose();});
 test(`${game}: ordinary exit serially saves latest after pending revN before teardown`,async()=>{const oldDocument=globalThis.document;globalThis.document={addEventListener(){},removeEventListener(){}};const f=fixture(game,room),gate=deferred();let first=true,held=false,unmounted=0,engine;const writes=[];f.hook=async(p,o)=>{if(p==='/api/save'){const b=JSON.parse(o.body);writes.push({b,keepalive:o.keepalive});if(first){first=false;held=true;await gate.promise;}}};const h=hostFactory({container:{replaceChildren(){}},fetch:f.fetch,interval:60000,mount:async(_,a)=>{await a.getState();engine={game:raw(game,room,2),saveTimer:1,saveState:'idle',async flushSave(keepalive){this.saveTimer=null;try{await a.save(game,this.game,{ownerId:'A',keepalive});this.saveState='saved';}catch(e){this.lastSaveError=e;this.saveState='failed';}}};return {engine,unmount(){unmounted++;if(engine.saveTimer)engine.flushSave(true);}};}});try{await h.start();const pending=h.adapter.save(game,raw(game,room,1),{ownerId:'A'});await until(()=>held);const exit=h.stop();await sleep(20);assert.equal(unmounted,0,'host must remain mounted until final ACK');gate.resolve();await pending;await exit;assert.equal(unmounted,1);assert.deepEqual(writes.map(x=>[x.b.revision,x.b.data.score,x.keepalive]),[[0,1,false],[1,2,false]]);}finally{gate.resolve();await h.destroy();globalThis.document=oldDocument;}});
 test(`${game}: failed final save keeps engine/recovery and retry succeeds`,async()=>{const oldDocument=globalThis.document;globalThis.document={addEventListener(){},removeEventListener(){}};const f=fixture(game,room);let fail=true,unmounted=0,engine;f.hook=p=>p==='/api/save'&&fail?Response.json({error:'Synthetic save failure'},{status:503}):undefined;const h=hostFactory({container:{replaceChildren(){}},fetch:f.fetch,interval:60000,mount:async(_,a)=>{await a.getState();engine={game:raw(game,room,7),saveTimer:1,async flushSave(keepalive){this.saveTimer=null;try{await a.save(game,this.game,{ownerId:'A',keepalive});this.saveState='saved';}catch(e){this.lastSaveError=e;this.saveState='failed';}}};return {engine,unmount(){unmounted++;}};}});try{await h.start();await assert.rejects(h.stop(),/Synthetic save failure/);assert.equal(h.handle.engine,engine);assert.equal(engine.game.score,7);assert.equal(unmounted,0);fail=false;await h.stop();assert.equal(unmounted,1);}finally{await h.destroy();globalThis.document=oldDocument;}});
}
