import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdirSync} from 'node:fs';
mkdirSync('evidence/screenshots',{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.RETRO_CHROMIUM || '/home/openclaw/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',args:['--no-sandbox']});
const checks=[],errors=[];const base='http://127.0.0.1:8787';
async function context(){const c=await browser.newContext({viewport:{width:1280,height:960}});await c.route('**/*',async route=>{const u=new URL(route.request().url());if(!['127.0.0.1','localhost'].includes(u.hostname))return route.abort();return route.continue();});return c;}
async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS',name);}
try {
const guest=await context(),page=await guest.newPage();page.on('pageerror',e=>errors.push(e.message));
await check('real browser catalog + disabled sale/notification + actual static headers',async()=>{const r=await page.goto(base);assert.equal(r.headers()['x-content-type-options'],'nosniff');await page.locator('#buyHero:disabled').waitFor();assert.equal(await page.locator('[data-wish]:disabled').count(),2);await page.screenshot({path:'evidence/screenshots/catalogue-disabled.png',fullPage:true});});
await check('real browser signup/signin failclosed UI without private credentials',async()=>{await page.getByRole('button',{name:'Sign up free',exact:true}).click();await page.locator('#suName').fill('Synthetic browser');await page.locator('#suEmail').fill('browser@example.test');await page.locator('#suGo').click();await page.locator('#suErr').filter({hasText:'not configured'}).waitFor();assert.equal(await guest.cookies().then(x=>x.filter(c=>c.name==='rq_session').length),0);await page.screenshot({path:'evidence/screenshots/signup-failclosed.png'});await page.keyboard.press('Escape');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.locator('#siEmail').fill('unknown@example.test');await page.locator('#siGo').click();await page.locator('#siErr').filter({hasText:'not configured'}).waitFor();await page.keyboard.press('Escape');});
await check('real browser denied admin then controlled mailbox proof enables admin',async()=>{await guest.addCookies([{name:'rq_session',value:'synthetic-session-admin',url:base,httpOnly:true,sameSite:'Lax'}]);await page.goto(base+'/admin.html');await page.locator('#gate:not([hidden])').waitFor();await page.goto(base+'/auth/link?token=synthetic-mailbox-proof-admin');await page.goto(base+'/admin.html');await page.locator('#main:not([hidden])').waitFor();await page.screenshot({path:'evidence/screenshots/verified-admin.png'});});
const playerContext=await context();await playerContext.addCookies([{name:'rq_session',value:'synthetic-session-player',url:base,httpOnly:true,sameSite:'Lax'}]);const player=await playerContext.newPage();player.on('pageerror',e=>errors.push(e.message));await player.goto(base);
async function dismiss(){while(await player.locator('#view .sierra').count())await player.locator('#view .sierra').first().click();}
async function cmd(text){await dismiss();await player.locator('#cmd').fill(text);await player.locator('#parserForm').evaluate(e=>e.requestSubmit());await player.locator('#view .sierra').first().waitFor();await dismiss();}
await check('real browser original suite mechanics + acknowledged CAS saves + paywall',async()=>{await player.locator('#playHero').click();await dismiss();await cmd('open minibar');await cmd('take crackers');await cmd('give crackers to goat');await cmd('take ticket');await cmd('use keycard on door');await player.locator('#view .overlay-card').waitFor();await player.waitForFunction(()=>document.querySelector('#saveStatus').textContent.startsWith('Saved'));await player.screenshot({path:'evidence/screenshots/suite-paywall.png'});});
await check('real browser admin grant + original garage continuation and puzzles',async()=>{const r=await page.evaluate(async()=>{return (await fetch('/api/admin/users/22222222-2222-4222-8222-222222222222/grant',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sku:'port-lucky'})})).status;});assert.equal(r,200);await player.waitForFunction(()=>!document.querySelector('#home').hidden);await player.locator('#playHero').click();await dismiss();await player.locator('#roomTxt').filter({hasText:'Parking garage'}).waitFor();await cmd('give ticket to valet');await cmd('use keys on truck');await cmd('take shoe');await cmd('take receipt');await player.locator('#view .overlay-card').waitFor();await player.waitForFunction(()=>document.querySelector('#saveStatus').textContent.startsWith('Saved'));await player.screenshot({path:'evidence/screenshots/garage-demo-end.png'});});
await check('real browser multi-device conflict retains pending; explicit reload; transport failure visible',async()=>{await player.locator('#view .overlay-card [data-a=back]').click();await player.locator('#playHero').click();await dismiss();const r=await player.evaluate(async()=>{const me=await (await fetch('/api/me')).json(),s=me.save_envelopes['port-lucky'];return (await fetch('/api/save',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({game_id:'port-lucky',...s,data:{...s.data,score:s.data.score+1}})})).status;});assert.equal(r,200);await player.locator('#retrySave').click();await player.locator('#saveStatus').filter({hasText:'Conflict'}).waitFor();await player.screenshot({path:'evidence/screenshots/save-conflict.png'});player.once('dialog',d=>d.accept());await player.locator('#reloadSave').click();await dismiss();await playerContext.route('**/api/save',r=>r.abort());await player.locator('#retrySave').click();await player.locator('#saveStatus').filter({hasText:'Not saved'}).waitFor();await player.screenshot({path:'evidence/screenshots/save-network-failure.png'});await playerContext.unroute('**/api/save');});
await check('real browser failed in-flight save retains newer pending gameplay snapshot',async()=>{
 let ready,release;const captured=new Promise(r=>ready=r),barrier=new Promise(r=>release=r);let first=true,next;
 await playerContext.route('**/api/save',async route=>{if(first){first=false;ready();await barrier;return route.abort();}next=route.request().postDataJSON();return route.continue();});
 await player.locator('#retrySave').click();await captured;await player.locator('#restartBtn').click();await dismiss();release();
 await player.locator('#saveStatus').filter({hasText:'Not saved'}).waitFor();await player.locator('#retrySave').click();await player.waitForFunction(()=>document.querySelector('#saveStatus').textContent.startsWith('Saved'));
 assert.ok(next.data.inv.includes('ticket'));assert.equal(next.data.flags.gotShoe,undefined);assert.equal(next.data.flags.demoDone,undefined);
 const server=await player.evaluate(async()=> (await (await fetch('/api/me')).json()).saves['port-lucky']);assert.equal(server.flags.gotShoe,undefined);assert.ok(server.inv.includes('ticket'));await playerContext.unroute('**/api/save');
});
await check('real browser entitlement loss tears down root and clears paid play',async()=>{await page.evaluate(async()=>fetch('/api/admin/users/22222222-2222-4222-8222-222222222222/revoke',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sku:'port-lucky'})}));await player.waitForFunction(()=>document.querySelector('#gameView').hidden);assert.equal(await player.locator('#view .overlay-card').count(),0);});
await check('service worker cache only controlled public icon/manifest allowlist',async()=>{await player.waitForFunction(async()=>{const r=await navigator.serviceWorker.getRegistration();return !!r?.active;});const urls=await player.evaluate(async()=>{const keys=await caches.keys(),out=[];for(const key of keys){const c=await caches.open(key);out.push(...(await c.keys()).map(r=>new URL(r.url).pathname));}return out;});assert.ok(urls.length>0);assert.ok(urls.every(p=>p.startsWith('/icons/')||p==='/manifest.webmanifest'));});
await check('real browser stale player refresh cannot undo local signout; drawer/menu teardown',async()=>{
 let captured,release;const ready=new Promise(r=>captured=r),barrier=new Promise(r=>release=r);
 let held=false;await playerContext.route('**/api/me',async route=>{if(held)return route.continue();held=true;const response=await route.fetch();captured();await barrier;await route.fulfill({response});});
 await player.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await ready;
 await player.locator('#nav').getByRole('button',{name:'Synthetic player',exact:true}).click();await player.getByRole('button',{name:'Sign out',exact:true}).click();
 await player.locator('#nav').getByRole('button',{name:'Sign in',exact:true}).waitFor();release();await playerContext.unroute('**/api/me');
 await player.waitForTimeout(1000);assert.equal(await player.locator('#nav').getByRole('button',{name:'Synthetic player',exact:true}).count(),0);assert.equal(await player.locator('#acctMenu').textContent(),'');assert.equal(await player.locator('#drawer').isVisible(),false);
});
const stubContext=await context(),stub=await stubContext.newPage();stub.on('pageerror',e=>errors.push(e.message));
await check('real browser inert seven-method adapter stub conflict + destroy/remount',async()=>{await stub.goto('http://127.0.0.1:8790');await stub.getByText('Mounted synthetic player A').waitFor();await stub.getByRole('button',{name:'Save inert snapshot'}).click();await stub.getByText('Not saved: Synthetic save conflict').waitFor();await stub.locator('#switch').click();await stub.getByText('Mounted synthetic player B').waitFor();await stub.locator('#revoke').click();await stub.locator('#counts').filter({hasText:'Mounts 3; destroys 2'}).waitFor();await stub.screenshot({path:'evidence/screenshots/inert-adapter.png'});});
assert.deepEqual(errors,[]);console.log(JSON.stringify({browser:'Actual local Chromium with Wrangler/local D1; external requests blocked. Stub and aborted-save cases labelled synthetic.',checks,pageErrors:errors},null,2));
} finally {await browser.close();}
