import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHmac} from 'node:crypto';
import worker from '../../src/index.js';
import {fixture,seed,call,mockNetwork,hash} from './helpers.js';
import {sendEmail} from '../../src/email.js';
import {createCheckout,verifyStripeSignature} from '../../src/stripe.js';
function pending(e,u,id='cs_1',sku='port-lucky'){e.DB.db.prepare('INSERT INTO purchases(id,user_id,sku,amount_cents,currency,status,created_at) VALUES(?,?,?,?,?,?,?)').run(id,u.id,sku,sku==='port-lucky'?799:199,'usd','pending',1);}
function complete(u,id='cs_1',pi='pi_1',sku='port-lucky'){return {id,payment_status:'paid',amount_total:sku==='port-lucky'?799:199,currency:'usd',payment_intent:pi,metadata:{user_id:u.id,sku},client_reference_id:u.id};}
async function webhook(e,type,obj,id=crypto.randomUUID(),bad=false){e.STRIPE_WEBHOOK_SECRET='synthetic-only';const raw=JSON.stringify({id,type,data:{object:obj}}),t=Math.floor(Date.now()/1000);const sig=createHmac('sha256',e.STRIPE_WEBHOOK_SECRET).update(t+'.'+raw).digest('hex');return worker.fetch(new Request('http://localhost/api/stripe/webhook',{method:'POST',headers:{'stripe-signature':`t=${t},v1=${bad?'00':sig}`},body:raw}),e,{});}
async function owned(e,u){return (await (await call(e,'/api/me',{token:u.token})).json()).entitlements;}
async function admin(e,a,u,action,sku){return call(e,`/api/admin/users/${u.id}/${action}`,{method:'POST',token:a.token,data:sku?{sku}: {}});}
const refund=pi=>({payment_intent:pi,refunded:true,amount:799,amount_refunded:799});
test('controlled mocked mailbox proof precedes admin and concurrent token consumes once',async()=>{const e=fixture(),net=mockNetwork();try{const r=await call(e,'/api/signup',{method:'POST',data:{email:'admin@example.test',name:'Synthetic',turnstile_token:'mock'}});assert.equal(r.status,200);const link=net.mailbox[0].text.match(/http:\/\/localhost\/auth\/link\?token=\S+/)[0];const rs=await Promise.all(Array.from({length:8},()=>call(e,new URL(link).pathname+new URL(link).search)));assert.equal(rs.filter(r=>r.headers.has('set-cookie')).length,1);const cookie=rs.find(r=>r.headers.has('set-cookie')).headers.get('set-cookie').split(';')[0].split('=')[1];assert.equal((await call(e,'/api/admin/stats',{token:cookie})).status,200);assert.equal(e.DB.db.prepare('SELECT count(*) n FROM sessions').get().n,1);}finally{net.restore();}});
test('login transaction failure rolls back token, identity and session',async()=>{const e=fixture(),u=seed(e,{verified:false});e.DB.db.prepare('INSERT INTO login_tokens(token_hash,user_id,created_at,expires_at) VALUES(?,?,?,?)').run(hash('proof'),u.id,1,Math.floor(Date.now()/1000)+1000);e.DB.db.exec("CREATE TRIGGER fail_verify BEFORE UPDATE OF verified_at ON users BEGIN SELECT RAISE(ABORT,'synthetic'); END");assert.equal((await call(e,'/auth/link?token=proof')).status,500);assert.equal(e.DB.db.prepare('SELECT used_at FROM login_tokens').get().used_at,null);assert.equal(e.DB.db.prepare('SELECT verified_at FROM users').get().verified_at,null);});
test('email missing config no logs/tokens; provider failure honest and redacted',async()=>{const e=fixture(),net=mockNetwork({fail:true}),logs=[];const old=console.log;console.log=(...x)=>logs.push(x);try{await assert.rejects(sendEmail({}, {to:'synthetic@example.test',text:'never-log-proof'}));for(const email of ['known@example.test','unknown@example.test']){if(email.startsWith('known'))seed(e,{email});const r=await call(e,'/api/login',{method:'POST',data:{email,turnstile_token:'mock'}});assert.equal(r.status,503);}assert.equal(e.DB.db.prepare('SELECT count(*) n FROM login_tokens').get().n,0);assert.ok(e.DB.db.prepare('SELECT * FROM email_log').all().every(x=>x.status==='failed'&&x.error==='Email provider unavailable'));assert.equal(logs.length,0);}finally{console.log=old;net.restore();}});
test('durable auth limits and anti-enumeration; protection fails closed',async()=>{const e=fixture(),net=mockNetwork();try{for(let i=0;i<5;i++)assert.equal((await call(e,'/api/login',{method:'POST',data:{email:'unknown@example.test',turnstile_token:'mock'}})).status,200);assert.equal((await call(e,'/api/login',{method:'POST',data:{email:'unknown@example.test',turnstile_token:'mock'}})).status,429);delete e.TURNSTILE_SECRET;assert.equal((await call(e,'/api/signup',{method:'POST',data:{email:'new@example.test',name:'Synthetic'}})).status,503);}finally{net.restore();}});
test('baseline populated migration preserves financial rows, legacy saves and grants',()=>{const e=fixture(false),u=seed(e);pending(e,u);e.DB.db.exec("UPDATE purchases SET status='paid'; INSERT INTO entitlements SELECT user_id,sku,1,'stripe' FROM purchases;");e.DB.db.prepare('INSERT INTO saves VALUES(?,?,?,?)').run(u.id,'port-lucky',JSON.stringify({room:'garage',flags:{demoDone:true}}),1);e.DB.db.exec(readFileSync('migrations/0002_hardening.sql','utf8'));assert.equal(e.DB.db.prepare('SELECT * FROM saves').get().revision,1);assert.equal(e.DB.db.prepare('SELECT * FROM entitlement_contributions').get().purchase_id,'cs_1');e.DB.db.prepare('DELETE FROM users WHERE id=?').run(u.id);assert.equal(e.DB.db.prepare('SELECT user_id FROM purchases').get().user_id,null);assert.deepEqual(e.DB.db.prepare('PRAGMA foreign_key_check').all(),[]);});
test('deletion rollback preserves all personal and financial records',async()=>{const e=fixture(),u=seed(e);pending(e,u);e.DB.db.exec("CREATE TRIGGER fail_delete BEFORE DELETE ON users BEGIN SELECT RAISE(ABORT,'synthetic'); END");assert.equal((await call(e,'/api/account',{method:'DELETE',token:u.token,data:{confirm:u.email}})).status,500);assert.equal(e.DB.db.prepare('SELECT user_id FROM purchases').get().user_id,u.id);assert.equal(e.DB.db.prepare('SELECT count(*) n FROM sessions').get().n,1);});
test('signed duplicate completion effects atomically once; invalid signatures/amounts rejected',async()=>{const e=fixture(),u=seed(e);pending(e,u);assert.equal((await webhook(e,'checkout.session.completed',complete(u),'bad',true)).status,400);assert.equal((await webhook(e,'checkout.session.completed',{...complete(u),amount_total:1})).status,400);const rs=await Promise.all(Array.from({length:8},()=>webhook(e,'checkout.session.completed',complete(u),'same')));assert.ok(rs.every(r=>r.status===200));assert.equal(e.DB.db.prepare('SELECT count(*) n FROM stripe_events').get().n,1);assert.equal(e.DB.db.prepare('SELECT count(*) n FROM entitlement_contributions').get().n,1);assert.deepEqual(await owned(e,u),['port-lucky']);});
test('refund before completion creates terminal tombstone; no late revival',async()=>{const e=fixture(),u=seed(e);pending(e,u);assert.equal((await webhook(e,'charge.refunded',refund('pi_1'))).status,200);assert.equal((await webhook(e,'checkout.session.completed',complete(u))).status,200);assert.equal(e.DB.db.prepare('SELECT status FROM purchases').get().status,'refunded');assert.deepEqual(await owned(e,u),[]);});
test('full refund removes only purchase contribution; admin and other purchase survive',async()=>{const e=fixture(),u=seed(e),a=seed(e,{email:'admin@example.test'});pending(e,u);pending(e,u,'cs_2');await webhook(e,'checkout.session.completed',complete(u));await webhook(e,'checkout.session.completed',complete(u,'cs_2','pi_2'));assert.equal((await admin(e,a,u,'grant','port-lucky')).status,200);await webhook(e,'charge.refunded',refund('pi_1'));await webhook(e,'checkout.session.completed',complete(u));assert.deepEqual(await owned(e,u),['port-lucky']);const rows=e.DB.db.prepare('SELECT * FROM entitlement_contributions WHERE revoked_at IS NULL').all();assert.equal(rows.length,2);assert.ok(rows.some(x=>x.source==='admin'));});
test('admin revocation survives late completion and walkthrough dependency enforced',async()=>{const e=fixture(),u=seed(e),a=seed(e,{email:'admin@example.test'});pending(e,u);assert.equal((await admin(e,a,u,'grant','port-lucky-walkthrough')).status,409);await admin(e,a,u,'revoke','port-lucky');await webhook(e,'checkout.session.completed',complete(u));assert.deepEqual(await owned(e,u),[]);await admin(e,a,u,'grant','port-lucky');await admin(e,a,u,'grant','port-lucky-walkthrough');assert.equal((await call(e,'/api/hint',{method:'POST',token:u.token,data:{game_id:'port-lucky',puzzle_id:'goat',level:0}})).status,200);await admin(e,a,u,'revoke','port-lucky');assert.equal((await call(e,'/api/hint',{method:'POST',token:u.token,data:{game_id:'port-lucky',puzzle_id:'goat',level:1}})).status,402);assert.deepEqual(await owned(e,u),[]);});
test('partial refund/dispute visibly reconcile without invented automatic policy',async()=>{const e=fixture(),u=seed(e);pending(e,u);await webhook(e,'checkout.session.completed',complete(u));await webhook(e,'charge.refunded',{...refund('pi_1'),refunded:false,amount_refunded:100});assert.equal(e.DB.db.prepare('SELECT status FROM purchases').get().status,'reconciliation-required');assert.deepEqual(await owned(e,u),['port-lucky']);await webhook(e,'charge.dispute.created',{payment_intent:'pi_unknown'});assert.equal(e.DB.db.prepare("SELECT status FROM payment_terminals WHERE payment_intent='pi_unknown'").get().status,'reconciliation-required');});
test('event effect failure rolls claim back for retry',async()=>{const e=fixture(),u=seed(e);pending(e,u);e.DB.db.exec("CREATE TRIGGER fail_grant BEFORE INSERT ON entitlement_contributions BEGIN SELECT RAISE(ABORT,'synthetic'); END");assert.equal((await webhook(e,'checkout.session.completed',complete(u),'retry')).status,500);assert.equal(e.DB.db.prepare('SELECT count(*) n FROM stripe_events').get().n,0);assert.equal(e.DB.db.prepare('SELECT status FROM purchases').get().status,'pending');e.DB.db.exec('DROP TRIGGER fail_grant');assert.equal((await webhook(e,'checkout.session.completed',complete(u),'retry')).status,200);});
test('CAS simultaneous devices one winner, stale rejected, accounts isolated, reset avoids ABA',async()=>{const e=fixture(),u=seed(e),b=seed(e,{email:'b@example.test'}),a=seed(e,{email:'admin@example.test'});const data={game_id:'port-lucky',version:1,revision:0,data:{score:1}};const rs=await Promise.all([call(e,'/api/save',{method:'PUT',token:u.token,data}),call(e,'/api/save',{method:'PUT',token:u.token,data:{...data,data:{score:2}}})]);assert.deepEqual(rs.map(r=>r.status).sort(),[200,409]);assert.equal((await call(e,'/api/save',{method:'PUT',token:b.token,data})).status,200);await admin(e,a,u,'reset-save');assert.equal((await call(e,'/api/save',{method:'PUT',token:u.token,data:{...data,revision:1}})).status,409);assert.equal((await (await call(e,'/api/me',{token:b.token})).json()).saves['port-lucky'].score,1);});
test('save JSON version, malformed and UTF-8 bounds; header and disabled sales',async()=>{const e=fixture(),u=seed(e);for(const version of [0,2])assert.equal((await call(e,'/api/save',{method:'PUT',token:u.token,data:{game_id:'port-lucky',version,revision:0,data:{}}})).status,400);assert.equal((await call(e,'/api/save',{method:'PUT',token:u.token,data:{game_id:'port-lucky',version:1,revision:0,data:{text:'漢'.repeat(22000)}}})).status,413);assert.equal((await call(e,'/api/checkout',{method:'POST',token:u.token,data:{sku:'port-lucky'}})).status,503);assert.equal((await call(e,'/api/dev/complete?session=cs')).status,404);const r=await call(e,'/');assert.equal(r.headers.get('x-content-type-options'),'nosniff');assert.equal(r.headers.get('cache-control'),'no-store');const unsafe=await worker.fetch(new Request('https://public.example.test/'),{...e,DEV_MODE:'1'},{});assert.equal(unsafe.status,503);});
test('admin audit minimal identifiers, reset and signout are effective',async()=>{const e=fixture(),u=seed(e),a=seed(e,{email:'admin@example.test'});await admin(e,a,u,'grant','port-lucky');await admin(e,a,u,'revoke','port-lucky');await admin(e,a,u,'reset-save');await admin(e,a,u,'signout');assert.equal((await (await call(e,'/api/me',{token:u.token})).json()).user,null);const rows=e.DB.db.prepare('SELECT * FROM admin_audit').all();assert.equal(rows.length,4);assert.ok(rows.every(x=>x.actor_id===a.id&&x.target_id===u.id&&!JSON.stringify(x).includes('@')));});
test('checkout provider request pins USD base amount without promotions or automatic tax',async()=>{let params;const old=fetch;globalThis.fetch=async(url,o)=>{params=new URLSearchParams(o.body);return Response.json({id:'cs_mock',url:'https://checkout.stripe.com/synthetic'});};try{await createCheckout({STRIPE_SECRET_KEY:'synthetic'},{product:{name:'Demo',price_cents:799},sku:'port-lucky',user:{id:'synthetic',email:'synthetic@example.test'},successUrl:'http://localhost',cancelUrl:'http://localhost'});assert.equal(params.get('allow_promotion_codes'),'false');assert.equal(params.get('automatic_tax[enabled]'),'false');assert.equal(params.get('line_items[0][price_data][unit_amount]'),'799');}finally{globalThis.fetch=old;}assert.equal(await verifyStripeSignature('{}','t=1,v1=00','synthetic'),false);});
