import test from 'node:test';import assert from 'node:assert/strict';
import {createMopGalaxyAdapter,createMopGalaxyHost} from '../../public/mop-galaxy-platform.js';
import {createPurchaseReturn} from '../../public/purchase-return.js';
const game='mop-galaxy';
const raw=(ownerId='A')=>({v:2,ownerId,chapter:1,room:'closet',inv:['mop'],flags:{},scored:{},score:0,hintsUsed:0,revealed:{},px:150,py:160,dir:1,started:true,clock:null,checkpoint:null,done:false});
function fixture(){let me={user:{id:'A',verified:true},entitlements:[],save_envelopes:{[game]:{version:1,revision:4,data:raw()}}},written=[],hooks={};return {get me(){return me;},set me(x){me=x;},written,hooks,fetch:async(p,o)=>{if(hooks[p])return hooks[p](o);if(p==='/api/me')return Response.json(me);if(p==='/api/config')return Response.json({catalog:{[game]:{price_cents:799}}});if(p==='/api/save'){const b=JSON.parse(o.body);written.push({b,o});return Response.json({acknowledged:true,revision:b.revision+1,updated_at:123});}return Response.json({revealed:[],count:0,text:'server hint'});}};}
test('Mop raw save stays inside v1 CAS envelope; serial writes and immediate keepalive',async()=>{const f=fixture(),b=createMopGalaxyAdapter({fetch:f.fetch});assert.equal((await b.refresh()).save.v,2);await b.adapter.save(game,raw(),{ownerId:'A'});await b.adapter.save(game,raw(),{ownerId:'A',keepalive:true});assert.deepEqual(f.written.map(x=>x.b.revision),[4,5]);assert.equal(f.written[1].o.keepalive,true);assert.equal(f.written[0].b.version,1);b.dispose();});
test('Mop reject cross-game methods/owner and retain conflict across polls',async()=>{const f=fixture(),b=createMopGalaxyAdapter({fetch:f.fetch});await b.refresh();await assert.rejects(b.adapter.save('port-lucky',raw(),{ownerId:'A'}));await assert.rejects(b.adapter.save(game,raw('B'),{ownerId:'A'}));await assert.rejects(b.adapter.revealHint('port-lucky','goat',0));f.hooks['/api/save']=()=>Response.json({error:'Save conflict'},{status:409});await assert.rejects(b.adapter.save(game,raw(),{ownerId:'A'}),e=>e.status===409);f.me.save_envelopes[game].revision=99;await b.refresh();delete f.hooks['/api/save'];await assert.rejects(b.adapter.save(game,raw(),{ownerId:'A'}),/Explicitly/);assert.equal(f.written.length,0);b.dispose();});
test('Mop stale hint/account/revocation invalidates bridge',async()=>{const f=fixture();f.me.entitlements=[game,game+'-walkthrough'];let resolve;const b=createMopGalaxyAdapter({fetch:f.fetch});await b.refresh();f.hooks['/api/hint']=()=>new Promise(r=>resolve=r);const p=b.adapter.revealHint(game,'snack-tool',0),rejected=assert.rejects(p,e=>e.code==='STATE_CHANGED');while(!resolve)await new Promise(r=>setTimeout(r,0));f.me={user:{id:'B',verified:true},entitlements:[]};await assert.rejects(b.refresh(),e=>e.code==='STATE_CHANGED');resolve(Response.json({text:'old private answer'}));await rejected;b.dispose();});
test('Mop serialized refresh never overwrites a pinned save/account',async()=>{const f=fixture(),rs=[];f.hooks['/api/me']=()=>new Promise(r=>rs.push(r));const b=createMopGalaxyAdapter({fetch:f.fetch});const first=b.refresh();while(!rs.length)await new Promise(r=>setTimeout(r,0));const last=b.refresh(),rejected=assert.rejects(last,e=>e.code==='STATE_CHANGED');assert.equal(rs.length,1);rs[0](Response.json(f.me));assert.equal((await first).user.id,'A');while(rs.length<2)await new Promise(r=>setTimeout(r,0));rs[1](Response.json({user:{id:'B',verified:true},entitlements:[]}));await rejected;b.dispose();});
test('Mop owner-pinned host and remount refuse switched account',async()=>{const old=globalThis.document;globalThis.document={addEventListener(){},removeEventListener(){}};const f=fixture();f.me.entitlements=[game];let live=0;const host=createMopGalaxyHost({container:{replaceChildren(){}},interval:60000,fetch:f.fetch,mount:async(_,a)=>{await a.getState();live++;return{unmount(){live--;}};}});try{await host.start('A');assert.equal(live,1);f.me.user.id='B';await assert.rejects(host.refresh());await host.stop();assert.equal(live,0);await assert.rejects(host.start('A'));assert.equal(host.handle,null);}finally{await host.destroy();globalThis.document=old;}});
test('Mop return is per-game bounded, authenticated and never accepts Port Lucky as Mop proof',async()=>{for(const owned of [[],['port-lucky'],[game]]){let calls=0,resumed=[],messages=[];const flow=createPurchaseReturn({read:async()=>{calls++;return{user:{id:'A',verified:true},entitlements:owned};},resume:async(s,id)=>resumed.push(id),status:s=>messages.push(s),wait:async()=>{},delays:[0,0]});await flow.run('success',game);assert.deepEqual(resumed,owned.includes(game)?[game]:[]);assert.equal(calls,owned.includes(game)?1:3);}});
test('Mop walkthrough/cancel/failed/wrong account never auto-resume',async()=>{for(const [result,sku,states] of [['cancelled',game,[['A',[game]]]],['failed',game,[['A',[game]]]],['success',game+'-walkthrough',[['A',[game,game+'-walkthrough']]]],['success',game,[['A',[]],['B',[game]]]]]){let i=0,resumed=0,m=[];const flow=createPurchaseReturn({read:async()=>{const [id,ent]=states[Math.min(i++,states.length-1)];return{user:{id,verified:true},entitlements:ent};},resume:async()=>resumed++,status:s=>m.push(s),wait:async()=>{},delays:[0,0]});await flow.run(result,sku);assert.equal(resumed,0);}});
