import test from 'node:test';import assert from 'node:assert/strict';
import {createPortLuckyAdapter,createPortLuckyHost} from '../../public/port-lucky-platform.js';
import {fixture,seed,call} from './helpers.js';
import {readFileSync} from 'node:fs';import {execFileSync} from 'node:child_process';import {PORT_LUCKY_HINTS} from '../../src/games/port-lucky-hints.js';
const game='port-lucky';
function fake(){let me={user:{id:'A'},entitlements:[game],save_envelopes:{[game]:{version:1,revision:4,data:{flags:{},score:10,room:'suite',inv:[]}}}},written=[],hooks={};const fetch=async(path,opts)=>{if(hooks[path])return hooks[path](opts);if(path==='/api/me')return Response.json(me);if(path==='/api/config')return Response.json({catalog:{[game]:{price_cents:799}}});if(path==='/api/save'){const b=JSON.parse(opts.body);written.push({b,opts});return Response.json({acknowledged:true,revision:b.revision+1,updated_at:123});}return Response.json({text:'private'});};return {fetch,written,hooks,get me(){return me;},set me(s){me=s;}};}
test('game bridge unwraps raw save and serializes current PUT CAS with actual ack and keepalive',async()=>{const f=fake(),b=createPortLuckyAdapter({fetch:f.fetch});const st=await b.adapter.getState();assert.deepEqual(st.save,{flags:{},score:10,room:'suite',inv:[]});assert.equal(st.catalog[game].price_cents,799);await b.adapter.save(game,{flags:{},score:11,ownerId:'A'},{ownerId:'A'});await b.adapter.save(game,{flags:{},score:12,ownerId:'A'},{ownerId:'A',keepalive:true});assert.deepEqual(f.written.map(x=>x.b.revision),[4,5]);assert.equal(f.written[1].opts.keepalive,true);assert.equal(f.written[0].b.version,1);assert.equal(f.written[0].opts.credentials,'same-origin');b.dispose();});
test('malformed existing saves latch automatic writes off without adopting a revision',async()=>{for(const data of [{},{flags:{},room:'unknown',inv:[],score:0},{flags:{},room:'suite',inv:[],score:0,v:99}]){const f=fake(),b=createPortLuckyAdapter({fetch:f.fetch});f.me.save_envelopes[game].data=data;await assert.rejects(b.refresh(),/invalid save retained/);await assert.rejects(b.adapter.save(game,{flags:{}},{ownerId:'A',keepalive:true}),/automatic writes are disabled/);assert.equal(f.written.length,0);b.dispose();}});
test('pagehide keepalive dispatches immediately behind a held ordinary write with strict CAS',async()=>{const f=fake(),b=createPortLuckyAdapter({fetch:f.fetch});await b.refresh();let release;const requests=[];f.hooks['/api/save']=opts=>{requests.push(opts);if(opts.keepalive)return Response.json({error:'Save conflict'},{status:409});return new Promise(r=>release=r);};const ordinary=b.adapter.save(game,{flags:{}},{ownerId:'A'});while(!release)await new Promise(r=>setTimeout(r,0));await assert.rejects(b.adapter.save(game,{flags:{}},{ownerId:'A',keepalive:true}),e=>e.status===409);assert.equal(requests.length,2);assert.equal(requests[1].keepalive,true);assert.equal(JSON.parse(requests[1].body).revision,4);release(Response.json({acknowledged:true,revision:5,updated_at:123}));await ordinary;b.dispose();});
test('bridge rejects unacknowledged writes without advancing CAS revision',async()=>{const f=fake(),b=createPortLuckyAdapter({fetch:f.fetch});await b.refresh();f.hooks['/api/save']=()=>Response.json({revision:5,updated_at:1});await assert.rejects(b.adapter.save(game,{flags:{}},{ownerId:'A'}),/not acknowledged/);delete f.hooks['/api/save'];await b.adapter.save(game,{flags:{}},{ownerId:'A'});assert.equal(f.written[0].b.revision,4);b.dispose();});
test('bridge retains CAS conflict across state polling; owner mismatch rejected before write',async()=>{const f=fake();let conflicts=0;const b=createPortLuckyAdapter({fetch:f.fetch,onConflict:()=>conflicts++});await b.refresh();await assert.rejects(b.adapter.save(game,{ownerId:'B'},{ownerId:'A'}),e=>e.status===409);assert.equal(f.written.length,0);f.hooks['/api/save']=()=>Response.json({error:'Save conflict'},{status:409});await assert.rejects(b.adapter.save(game,{flags:{}},{ownerId:'A'}),e=>e.status===409);f.me.save_envelopes[game].revision=99;await b.refresh();delete f.hooks['/api/save'];await assert.rejects(b.adapter.save(game,{flags:{}},{ownerId:'A'}),/Explicitly/);assert.equal(f.written.length,0);assert.equal(conflicts,1);b.dispose();});
test('bridge stale hint response discarded on actual observed identity/access change',async()=>{const f=fake();let resolveHint,changed=0;const b=createPortLuckyAdapter({fetch:f.fetch,onAccessChange:()=>changed++});await b.refresh();f.hooks['/api/hint']=()=>new Promise(r=>resolveHint=r);const pending=b.adapter.revealHint(game,'goat',0);const rejected=assert.rejects(pending,e=>e.code==='STATE_CHANGED');while(!resolveHint)await new Promise(r=>setTimeout(r,0));f.me={user:{id:'B'},entitlements:[]};await assert.rejects(b.refresh(),e=>e.code==='STATE_CHANGED');resolveHint(Response.json({text:'private A text'}));await rejected;assert.equal(changed,1);b.dispose();});
test('bridge does not expose a hint revoked between hint request and acknowledgement',async()=>{const f=fake();f.me.entitlements.push(game+'-walkthrough');let changes=0;const b=createPortLuckyAdapter({fetch:f.fetch,onAccessChange:()=>changes++});await b.refresh();f.hooks['/api/hint']=()=>{f.me.entitlements=[game];return Response.json({text:'revoked private text'});};await assert.rejects(b.adapter.revealHint(game,'goat',0),e=>e.code==='STATE_CHANGED');assert.equal(changes,1);b.dispose();});
test('bridge out-of-order state cannot restore stale entitlement or save owner',async()=>{const f=fake(),resolves=[];f.hooks['/api/me']=()=>new Promise(r=>resolves.push(r));const b=createPortLuckyAdapter({fetch:f.fetch});const old=b.refresh(),denied=assert.rejects(old,e=>e.code==='STATE_CHANGED');const newer=b.refresh();resolves[1](Response.json({user:{id:'B'},entitlements:[]}));assert.equal((await newer).user.id,'B');resolves[0](Response.json(f.me));await denied;b.dispose();});
test('server owner guard rejects both outer ownerId and raw game ownerId; no D1 mutation',async()=>{const e=fixture(),a=seed(e);for(const data of [{ownerId:'other',data:{}},{data:{ownerId:'other'}}]){const r=await call(e,'/api/save',{token:a.token,method:'PUT',data:{game_id:game,version:1,revision:0,...data}});assert.equal(r.status,409);}assert.equal(e.DB.db.prepare('SELECT count(*) n FROM saves').get().n,0);});
test('all 28 authoritative puzzles stay server-only and cover drawing source is byte exact',()=>{assert.equal(Object.keys(PORT_LUCKY_HINTS).length,28);const old=execFileSync('git',['show','c5082396ddf53f4c5033ea4237264de3094608aa:public/index.html'],{encoding:'utf8'}),art=readFileSync('public/landing-art.js','utf8');for(const [a,b] of [['/* ---------- Palette','/* ---------- Storage'],['/* ---------- Drawing: Suite','/* ---------- Drawing: Garage'],['/* ---------- Covers','/* ---------- Game render loop']])assert.ok(art.includes(old.slice(old.indexOf(a),old.indexOf(b))));const sw=readFileSync('public/sw.js','utf8');assert.match(sw,/static-v5/);assert.doesNotMatch(sw,/\/api\/|port-lucky-hints/);});
test('host serializes rapid start/stop and removes old engine before remount',async()=>{const previous=globalThis.document;globalThis.document={addEventListener(){},removeEventListener(){}};let count=0,live=0,max=0;const host=createPortLuckyHost({container:{replaceChildren(){}},interval:100000,mount:async()=>{await new Promise(r=>setTimeout(r,5));count++;live++;max=Math.max(max,live);return {unmount(){live--;}};}});try{await Promise.all([host.start(),host.start(),host.stop()]);assert.equal(count,2);assert.equal(max,1);assert.equal(live,0);}finally{await host.destroy();globalThis.document=previous;}});
