import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';
const base='http://127.0.0.1:8787',admin='11111111-1111-4111-8111-111111111111',buyer='33333333-3333-4333-8333-333333333333';
const results=[];async function check(name,fn){await fn();results.push({name,status:'PASS'});console.log('PASS',name);}
async function api(path,{token,method='GET',data,raw,headers={},redirect='manual'}={}){return fetch(base+path,{method,redirect,headers:{...(token?{cookie:'rq_session='+token}:{}),...(data?{'content-type':'application/json'}:{}),...headers},body:raw??(data?JSON.stringify(data):undefined)});}
let privileged;
await check('actual Worker headers + catalog disable sale + fixture paths not shipped',async()=>{const r=await api('/');assert.equal(r.status,200);assert.equal(r.headers.get('x-content-type-options'),'nosniff');assert.equal(r.headers.get('cache-control'),'no-store');assert.equal((await (await api('/api/config')).json()).saleEnabled,false);assert.equal((await api('/dev/platform/stub.js')).status,404);});
await check('actual D1 unverified seeded admin denied',async()=>{assert.equal((await api('/api/admin/stats',{token:'synthetic-session-admin'})).status,403);assert.equal((await (await api('/api/me',{token:'synthetic-session-admin'})).json()).user.isAdmin,false);});
await check('actual D1 simultaneous controlled mailbox proof consumes once',async()=>{const rs=await Promise.all(Array.from({length:8},()=>api('/auth/link?token=synthetic-mailbox-proof-admin')));const valid=rs.filter(r=>r.headers.has('set-cookie'));assert.equal(valid.length,1);privileged=valid[0].headers.get('set-cookie').split(';')[0].slice('rq_session='.length);assert.equal((await api('/api/admin/stats',{token:privileged})).status,200);});
await check('actual runtime missing auth/mail configuration honest 503, no public hook',async()=>{const r=await api('/api/signup',{method:'POST',data:{email:'new@example.test',name:'Synthetic'}});assert.equal(r.status,503);assert.equal(r.headers.get('set-cookie'),null);assert.equal((await r.json()).dev_link,undefined);});
await check('actual D1 concurrent CAS and stale revisions; server acknowledgement',async()=>{const data={game_id:'port-lucky',version:1,revision:1,data:{room:'suite',inv:[],flags:{},scored:{},score:1,hintsUsed:0,revealed:{},px:150,py:160,started:true}};const rs=await Promise.all(Array.from({length:8},()=>api('/api/save',{method:'PUT',token:'synthetic-session-player',data})));assert.equal(rs.filter(r=>r.status===200).length,1);assert.equal(rs.filter(r=>r.status===409).length,7);assert.equal((await rs.find(r=>r.status===200).json()).revision,2);assert.equal((await (await api('/api/me',{token:privileged})).json()).save_envelopes['port-lucky'],undefined);});
await check('actual D1 hint authorization and admin dependency/audit',async()=>{assert.equal((await api('/api/hint',{method:'POST',token:'synthetic-session-player',data:{game_id:'port-lucky',puzzle_id:'goat',level:0}})).status,402);assert.equal((await api('/api/admin/users/'+buyer+'/grant',{method:'POST',token:privileged,data:{sku:'port-lucky-walkthrough'}})).status,409);assert.equal((await api('/api/admin/users/'+buyer+'/grant',{method:'POST',token:privileged,data:{sku:'port-lucky'}})).status,200);const rows=(await (await api('/api/admin/audit',{token:privileged})).json()).audit;assert.ok(rows.some(x=>x.actor_id===admin&&x.action==='grant'));});
const done={id:'cs_runtime',payment_status:'paid',currency:'usd',amount_total:799,payment_intent:'pi_runtime',client_reference_id:buyer,metadata:{user_id:buyer,sku:'port-lucky'}};
async function event(type,obj,id){const raw=JSON.stringify({id,type,data:{object:obj}}),t=Math.floor(Date.now()/1000),sig=createHmac('sha256','synthetic-local-only-not-a-provider-secret').update(t+'.'+raw).digest('hex');return api('/api/stripe/webhook',{method:'POST',raw,headers:{'stripe-signature':`t=${t},v1=${sig}`}});}
await check('actual D1 signed simultaneous duplicates and refund ordering/provenance',async()=>{const rs=await Promise.all(Array.from({length:6},()=>event('checkout.session.completed',done,'evt_runtime')));assert.ok(rs.every(r=>r.status===200));await event('charge.refunded',{payment_intent:'pi_runtime',refunded:true,amount:799,amount_refunded:799},'evt_refund');await event('checkout.session.completed',done,'evt_late');const me=await (await api('/api/me',{token:'synthetic-session-buyer'})).json();assert.deepEqual(me.entitlements,['port-lucky']);const d=await (await api('/api/admin/users/'+buyer,{token:privileged})).json();assert.equal(d.purchases[0].status,'refunded');});
await check('actual D1 deletion retains detached financial record',async()=>{assert.equal((await api('/api/account',{method:'DELETE',token:'synthetic-session-buyer',data:{confirm:'buyer@example.test'}})).status,200);assert.equal((await (await api('/api/me',{token:'synthetic-session-buyer'})).json()).user,null);const s=await (await api('/api/admin/stats',{token:privileged})).json();const p=s.recent.find(x=>x.id==='cs_runtime');assert.equal(p.status,'refunded');assert.equal(p.email,null);});
console.log(JSON.stringify({runtime:'Wrangler/workerd + local D1 (not live providers)',results},null,2));
